# Generated by Django 3.1.3 on 2020-11-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_forward', models.BooleanField(default=False)),
                ('wait_time', models.BooleanField(default=False)),
                ('wait_alerts', models.BooleanField(default=False)),
                ('wait_for_choose_channel', models.BooleanField(default=False)),
                ('current_channel_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('alert_times', models.IntegerField(default=1)),
                ('alerts_left', models.IntegerField(default=2)),
                ('disabled', models.BooleanField(default=False)),
                ('period', models.IntegerField(default=0)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.chat')),
            ],
        ),
    ]
