# Generated by Django 3.1.3 on 2020-11-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user_wait_forward'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Chat',
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.chat')),
            ],
        ),
    ]
