# Generated by Django 3.1.3 on 2020-11-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201108_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='current_channel_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
