# Generated by Django 3.1.3 on 2020-11-08 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_chat_current_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
