# Generated by Django 3.1.3 on 2020-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_channel_last_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='wait_for_choose_channel',
            field=models.BooleanField(default=False),
        ),
    ]
