# Generated by Django 3.1.3 on 2020-11-09 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_chat_wait_for_choose_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NewChannel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_id', models.IntegerField()),
                ('disabled', models.BooleanField(default=False)),
                ('period', models.IntegerField(default=0)),
                ('last_message_time', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.chat')),
            ],
        ),
    ]
