# Generated by Django 3.1.3 on 2020-11-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20201109_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
