# Generated by Django 3.1.3 on 2020-11-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_auto_20201110_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='alerts_left',
            field=models.IntegerField(default=2),
        ),
    ]
